# Generated by Django 5.0.6 on 2024-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_msg',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('url', models.TextField(max_length=150)),
                ('intruduction', models.TextField(max_length=150)),
                ('pic', models.TextField(max_length=150)),
                ('up_time', models.TextField(max_length=150)),
            ],
        ),
    ]
